version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdownlint-cli
    versions:
    - 0.26.0
    - 0.27.0
